### ISSUE TITLE
rename table names => sakuli

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#10]
instead of sahi

**Comment by toschneck** [comment]
* rename table names in code
* adjust sql-creation script
* write a small mirgration script
* update the documenation

**Comment by simonmeggle** [comment]
+adapt mysql_purge.sh script

**Comment by toschneck** [comment]
@simonmeggle my code changes  are done. I also modified the perl module and mysql_purge.sh, but i  couldn't test it. Can you please look over it and then close the issue?

**Comment by simonmeggle** [comment]
check migration script
