### ISSUE TITLE
add an option to cache check results

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#101]
Sakuli clients should be able to cache check results when the receiving gearman server ist not available.

**Comment by toschneck** [comment]
it have to be ensured, that the realy execution timestamp will be used for the nagios result output

**Comment by simonmeggle** [comment]
Check the order of incoming cached results in OMD/Nagios/PNP

**Comment by toschneck** [comment]
@christophd I have done some smaller changes during my review, can you take a look at it, and if all is ok close this ticket?
