### ISSUE TITLE
enable drag and drop

### ISSUE THREAD

**Issue by lhoe** [ConSol/sakuli#102]
`mouseDown` currently locks the mouse movement and aren't able to do a `mouseUp` again. Solution might be to use the hover method or to enable drag and drop directly

```
var pdf = screen.waitForImage("pdf_test.png", 10);
var tb = screen.waitForImage("taskbar_browser.png", 10);
pdf.mouseMove();
screen.mouseDown(MouseButton.LEFT);
tb.mouseMove();
screen.mouseUp(MouseButton.LEFT);
```

**Comment by sni** [comment]
sikuli has dd support: http://doc.sikuli.org/region.html?highlight=dropat#Region.dragDrop
Would be cool to have something like that too.

**Comment by toschneck** [comment]
Is now on `dev` branch avaible like follow
```
var bubble = screen.find("bubble.png");
bubble.dragAndDropTo(bubble.right(20));
```
