### ISSUE TITLE
warn/crit thresholds as perfdata values

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#106]
Currently runtime thresholds e.g. for a suite (50,60) are transmitted within the runtime perfdata label: 

    suite_sakuli_demo22=44s;50;60;;

PNP stores only "44s" in rrdtool, thresholds however are saved in the check's XML file and displayed in the graph as a HRULE, only describing the *last* set threshold, not what other thresholds were defined in the past. 

To draw w/c thresholds also as a "real" line, we need them as perfdata labels, too:

    suite_sakuli_demo22_warning=50s;;;;
    suite_sakuli_demo22_critical=60s;;;;
    c_001_oxid_showcase_warning=10s;;;;
    c_001_oxid_showcase_critical=12s;;;;
    c_002_calculator_warning=15s;;;;
    c_002_calculator_critical=19s;;;;
    ....

**Comment by toschneck** [comment]
Format will be like:
only for suites and cases
```
suite__state 			0
suite__warning	 		120s
suite__critical			140s
...
c_002__state			0			
c_002__warning			80s			
c_002__critical			100s	
```

**Comment by toschneck** [comment]
changes in code done:

@simonmeggle review german performance graph template + adjust DB performance data generation
__Gearman based result__
![performance_data_gearman](https://cloud.githubusercontent.com/assets/4659261/10058999/b02b45d4-6248-11e5-8ccd-412543913cb9.png)

__DB based result__
![performance_data_db](https://cloud.githubusercontent.com/assets/4659261/10058986/93e444c0-6248-11e5-8de6-7d1e7b62943c.png)

**Comment by simonmeggle** [comment]
TODO: DB module adaption
