### ISSUE TITLE
introduce port parameter for sahi proxy

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#11]
set xvnc Display ID and ports dependent on that port. 
=> allows parallel execution on linux

**Comment by simonmeggle** [comment]
Check first #7 , then adapt port parameter

**Comment by simonmeggle** [comment]
(Any news on that?)

**Comment by toschneck** [comment]
Still waiting to do #7 first ;-)

**Comment by simonmeggle** [comment]
Ah. :+1:

**Comment by toschneck** [comment]
@simonmeggle will you do the documenation task?
The effected property in sakuli-default.properties is 'sahi.proxy.port'

**Comment by simonmeggle** [comment]
Different port for each headless check!

**Comment by toschneck** [comment]
add information to doku https://github.com/ConSol/sakuli/blob/master/docs/headless-linux.md

**Comment by simonmeggle** [comment]
A port parameter for Sahi won' work as desired, i'm afraid. 

Setting `proxy.port=10000` in userdata.properties` is only half the truth. Sahi indeed starts and listens on port 10000, but there is no way to tell the *browser* that it should connect to that port. This information is kind of hardcoded in sahi.properties/userdata.properties and can't be changed at runtime. Changing the proxy settings of prefs.js with increasing port numbers in sahi0, sahi1, sahi2, .... and creating browser profiles for them would be the only solution, but is a mess. 
Seems like we have to stick on Sahi port 9999. Parallel tests would definitely require an isolated environment like Docker. Hmpf.

**Comment by simonmeggle** [comment]
No further investigations for headless *and* parallel execution. In this case, Docker is the preferred way.
