### ISSUE TITLE
gearman: warning in step -> wrong status in case

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#118]
To reproduce: overall status WARNING, *one* step over allowed runtime. 
Gearman output is: 

![bildschirmfoto 2015-10-09 um 17 13 44](https://cloud.githubusercontent.com/assets/1897410/10397656/17e0174c-6ea9-11e5-872c-f8e3583fda30.png)

This is not correct; the case itself did not exceed its runtime. For comparison, see DB output: 

![bildschirmfoto 2015-10-09 um 17 12 47](https://cloud.githubusercontent.com/assets/1897410/10397625/f742c106-6ea8-11e5-8f79-13fe78c68007.png)

**Comment by toschneck** [comment]
@simonmeggle check if still present
