### ISSUE TITLE
sakuli.jar: console output improvements

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#121]
Usage does not tell clearly enough which parameters are mandatory. 
Proposal for a different format and order of parameters: 
- distunguish between MODE and OPTIONS
- remove `sahi_home` and `sakuli_home` as parameter, because any property can be set with _-D_. Perhaps solely leave --browser, as it will be used most often. 

```
usage: sakuli MODE [OPTIONS]
MODES: 
 -r,--run <test-suite-folder>       run a sakuli test suite
 -e,--encrypt <secret>              encrypt a secret
OPTIONS: 
 -b,--browser <browser>             (optional) browser for the test execution,
                                    default: property 'testsuite.browser'
 -i,--interface <interface-name>    (optional) network interface used for mode
                                    encryption, default: auto-selection
 -Dany.property.key=value           JVM option to set property on runtime
 -h,--help                          display this help
```

**Comment by simonmeggle** [comment]
Perhaps also print out usage() when calling the starter without a mode (--run/--encrypt) instead of

    ./sakuli.sh -b firefox
    Error: Could not find or load main class

**Comment by toschneck** [comment]
no longer needed #231
