### ISSUE TITLE
check_sakuli.php: Suite ticker - incomplete data show up as red ticker

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#129]
![bildschirmfoto 2015-10-23 um 22 00 20](https://cloud.githubusercontent.com/assets/1897410/10704254/c92f515c-79d5-11e5-82a5-f546e19ddfde.png)

**Comment by toschneck** [comment]
recommended graph solution is grafana, so pnp4nagios is a little bit depreciated
