### ISSUE TITLE
Sakuli: unpredictable results with similarity=1.0?

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#135]
We should test again how the SikuliX version behaves with similarities of 1.0. 
Last result with this level were terrible.

**Comment by simonmeggle** [comment]
We should consider to set 0.99 as default similarity. 
In doubt, it is better that Sikuli rates more strictly.

**Comment by toschneck** [comment]
- [ ] SM: Test similarity, if some unexpected issues will occur, win and linux
- [ ] TS: Extract constant `Environment#DEFAULT_SIMILARITY` to sakuli-default.properties`

**Comment by sgbeal** [comment]
FWI: comparison of floating point number is unreliable in the general case and this problem is not solvable:

http://floating-point-gui.de/errors/comparison/
http://stackoverflow.com/questions/12693890/why-does-1-0-not-equal-to-1-0-in-tcl-when-using
http://www.purplemath.com/modules/howcan1.htm

etc etc etc etc etc

**Comment by toschneck** [comment]
@simonmeggle: some more infos about how sikulix screen pattern recognation works:
https://github.com/RaiMan/SikuliX-2014/issues/148#issuecomment-116253860

**Comment by simonmeggle** [comment]
Not a real issue. As seen in http://sikulix-2014.readthedocs.org/en/latest/basicinfo.html#sikulix-how-does-it-find-images-on-the-screen: 
Similarity is taken as a "higher-than" value, that means for a match candidate region that _more than_ $similarity percent of the region's pixels must coincide. Hence, the highest possible similarity we can set is in fact **0.99** - (1.00 would mean that more than 100% pixels must match. Would be hard to achieve... )

**As discussed, lets set the default similarity to 0.99.** Decreasing this value should onyl be neccessary if the pattern images are of poor quality or the screen always differs slightly from the pattern images (e.g. compression of remote sessions like vnc). 

Documentation is already done in 1cc3c8d193e383f08e9670773e4509adc16049db.
