### ISSUE TITLE
introduce sakuli.screenshots.wait

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#14]
After calling the screenshot routine, wait 1-2s. Some screenshots currently do not show the application's error anymore but everything already closed.  

=> introduce new property: 
sakuli.screenshots.wait = 2
(see also https://github.com/ConSol/sakuli/issues/13)

**Comment by toschneck** [comment]
* check duration of screenshot duration
  * test case which capture a running timer
  * check log-files
  * check sahi and sikuli methods

**Comment by toschneck** [comment]
should be already solved
