### ISSUE TITLE
Folder Parsing Problem on Windows

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#142]
Under windows there is some issue if an Path will contains quotes, like 
```
    @Test
    public void testWindowsTilde() throws Exception {
        Paths.get("\"C:\\PROGRA~1\\.\"").normalize();

    }
```
![2015-11-16 17_31_27-greenshot](https://cloud.githubusercontent.com/assets/4659261/11190181/9d3dff22-8c94-11e5-882f-e9786428c8d1.png)

**Comment by toschneck** [comment]
Problem is only under Windows present and depends on the java.nio.Path implementation on windows which throws a Parsing-Exception in the `sun.nio.fs.WindowsPathParser`. On linux no Problem occurs with `"` in the strings. 

__Solution:__ remove all `"` in Strings parsed into the SakuliStarter
![image](https://cloud.githubusercontent.com/assets/4659261/11237617/453daea0-8de1-11e5-98e7-bd506c7a68bf.png)

**Comment by sgbeal** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

double-quotes are reserved characters in Windows.
