### ISSUE TITLE
new forwarder: icinga2-API

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#145]
See http://docs.icinga.org/icinga2/snapshot/doc/module/icinga2/chapter/icinga2-api, 
-> "process-check-result"

**Comment by toschneck** [comment]
vagrant-vm: https://github.com/Icinga/icinga-vagrant/tree/master/icinga2x

**Comment by simonmeggle** [comment]
`curl -k -s -u root:rootroot -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/actions/process-check-result?service=sakuliclient01!sakuli_demo' -d '{
    "check_source": "check_sakuli",
    "exit_status": 0,
    "performance_data": [
"s_001_001_Test_Sahi_landing_page=1.96s;15;;;",
"s_001_002_Calculation=8.96s;30;;;",
"s_001_003_Editor=8.38s;30;;;",
"c_001_case1=25.22s;40;50;;",
"c_001__state=0;;;;",
"c_001__warning=40s;;;;",
"c_001__critical=50s;;;;",
"suite__state=0;;;;",
"suite__warning=50s;;;;",
"suite__critical=60s;;;;"
    ],
    "plugin_output": "Sakuli suite 'example_ubuntu_0' (ID: 25100) ran in 42.31 seconds."
}'`

**Comment by toschneck** [comment]
@simonmeggle add docu:
* forward as markdown docu
* sakuli-default.properties

**Comment by simonmeggle** [comment]
Displaying URI-base64-encoded images of error screenshots will not be possible, because HTMLPurifier replaces also semicolon by a double colon for safety reasons: 
` src="data:image/jpg;base64,iVBORw0KGgoAAAANSUhEU`
becomes
` src="data:image/jpg:base64,iVBORw0KGgoAAAANSUhEU`
