### ISSUE TITLE
Add option to installer to change registry settings for RDP connections 

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#151]
as described in https://github.com/ConSol/sakuli/blob/dev/docs/troubleshooting-tuning-sakuli-client.md

**Comment by toschneck** [comment]
also add UTF-8 support:
set under `HKEY_Current_User\Control Panel\Input Method` the key `EnableHexNumpad` to `1`

* maybe implent this via java class to be more reliable

**Comment by simonmeggle** [comment]
[ HKEY_CURRENT_USER\Control Panel\Desktop ]
"ForegroundLockTimeout" (DWORD) => "0" (default = 30d40xh)

[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics ]
"MinAnimate" (String) => "0" 

[ HKEY_CURRENT_USER\Control Panel\Desktop ]
"FontSmoothingType" (DWORD) => "0" 

[ HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects ]
"VisualFXSetting" (DWORD) => "2"

[ HKEY_CURRENT_USER\Software\Microsoft\Windows\Windows Error Reporting ]
"Disabled" (DWORD) => "1"

**Comment by simonmeggle** [comment]
Proposal: add options for each registry key (default: checked) to allow individual settings, if needed.

**Comment by simonmeggle** [comment]
As discussed, registry settings for RDP were deleted from the documentation because they will be set automatically by the installer.
