### ISSUE TITLE
Installer: add env variable MOZ_DISABLE_AUTO_SAFE_MODE

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#158]
`MOZ_DISABLE_AUTO_SAFE_MODE = 1`

To prevent Firefox starting in safe mode.

**Comment by toschneck** [comment]
* set also under linux
* add to linux envs `MOZ_OOP_DISABLE_PLUGINS`

**Comment by simonmeggle** [comment]
Both variables should be system env variables, not user env variables to allow test execution also in another user context.

**Comment by toschneck** [comment]
Maybe a stucking SHIFT-KEY let start the firefox in safe-mode. Set MOZ_DISABLE_SAFE_MODE_KEY will solve this. See http://stackoverflow.com/questions/10111026/disable-change-firefox-safe-mode-hotkey-shift
