### ISSUE TITLE
Certificate not found

### ISSUE THREAD

**Issue by sni** [ConSol/sakuli#170]
When using the latest 1.0.0, i get some certificate warnings for google-chrome:

```
WARN  [2016-03-04 15:57:37.109] - 
----
Certificate not found: /root/sakuli/sahi/userdata/certs/clients1_google_com
----
WARN  [2016-03-04 15:57:37.305] - 
----
Certificate not found: /root/sakuli/sahi/userdata/certs/ssl_gstatic_com
----
WARN  [2016-03-04 15:57:37.422] - 
----
Certificate not found: /root/sakuli/sahi/userdata/certs/ssl_gstatic_com
----
```

Besides the actual warning, it would be nice to print the warning on the same line as the WARN... itself.    

This is the relevant part from my browser_types/linux.xml

```
<browserType>
        <name>chrome</name>
        <displayName>Chrome</displayName>
        <icon>chrome.png</icon>
        <path>/usr/bin/google-chrome</path>
        <options>--incognito --no-sandbox --no-default-browser-check --no-first-run --disable-infobars --user-data-dir=$userDir/browser/chrome/profiles/sahi$threadNo --start-maximized --no-default-browser-check --no-first-run --disable-infobars --proxy-server=localhost:9999 --disable-popup-blocking</options>
        <processName>chrome</processName>
        <capacity>5</capacity>
    </browserType>
</browserTypes
```

**Comment by toschneck** [comment]
The log messages are produced by sahi and just say, that these certificates are not yet created, so sahi create some new self-signed certificates. In that case google calls in background to some static sites. will be solved with #131. Alternatively you can prevent the logging if you set down the sahi log level: `log.level.sahi=ERROR`
