### ISSUE TITLE
New Forwarder: check_mk

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#176]

**Comment by kash1983** [comment]
really need an forwarder to check_mk and i think many guys too

**Comment by simonmeggle** [comment]
Example Output: 
```
[OK] Sakuli suite "example_xfce" ok (27.02s). (Last suite run: 30.05.16 21:54:04) | suite__state=0;;;; suite__warning=30s;;;; suite__critical=40s;;;; suite_example_xfce=27.02s;30;40;; c_001__state=0;;;; c_001__warning=20s;;;; c_001__critical=30s;;;; c_001_case1=14.65s;20;30;; s_001_001_Test_Sahi_landing_page=1.71s;5;;; s_001_002_Calculation=7.23s;10;;; s_001_003_Editor=1.61s;10;;;
```
should be formatted as
```
0 example_xfce [OK] suite__state=0|suite__warning=30s| suite__critical=40s|suite_example_xfce=27.02s;30;40;;| c_001__state=0|c_001__warning=20s|c_001__critical=30s| c_001_case1=14s;20;30|s_001_001_Test_Sahi_landing_page=1.71s|s_001_002_Calculation=7.23s;10|s_001_003_Editor=1.61s;10 [OK] Sakuli suite "example_xfce" ok (27.02s). (Last suite run: 30.05.16 21:54:04)
```

- Use a template engine 
- Write result file into spool folder of check_mk: [https://mathias-kettner.de/check_mk_werks.php?werk_id=0016&HTML=yes](https://mathias-kettner.de/check_mk_werks.php?werk_id=0016&HTML=yes)
- **new properties**:
-- `sakuli.forwarder.check_mk.enabled` - enable forwarder
-- `sakuli.forwarder.check_mk.freshness` - max result age. Otherwise the check will turn into UNKNOWN 
- Integrate screenshots into multisite GUI (eventhandler -> screenshot history)

**Comment by simonmeggle** [comment]
Remark: the spool file must have a timestamp which is younger than "now-freshness". Otherwise the check discovery will not inventory the new checks.

**Comment by simonmeggle** [comment]
Checked the forwarder functionality & template. 
The only unresolved issue is that the data URI encoded screenshot image is not displayed properly: `data:image/jpg;base64` gets replaced by `data:image/jpg:base64`. No clue. Perhaps some MK user can ask for support there.

**Comment by simonmeggle** [comment]
Write documentation

**Comment by simonmeggle** [comment]
Reviewed the documentation.
