### ISSUE TITLE
function waitForWindow

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#18]
e.g. 

    var loginregion = screen.waitForWindow("enter credentials", 10); 

=> Bring window to foreground using its title

**Comment by toschneck** [comment]
Functionality is already included in the `Application` class.  See herfore the link: http://sikulix-2014.readthedocs.org/en/latest/appclass.html

**TODO => Update the sakuli documentation related to this**

**Comment by simonmeggle** [comment]
:+1: 

    App.focus("Firefox")
