### ISSUE TITLE
.gearman-cache: CR/LF on Windows

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#183]
Ensure that the gearman cache file gets written in Unix style. It seems to contain CR characters which lead to false host/service names in Nagios: 

> [1462290930] Warning: Check result queue contained results for service 'Test^M' on host '01_Test^M', but the service could not be found!  Perhaps you forgot to define the service in your config files?

**Comment by simonmeggle** [comment]
Line breaks are not consistent yet. Steps to reproduce on a Windows box: 
* remove cache file
* disable germand 
* start example test case 3 times, cache file will be created

The cache file now contains: 

``` 
...
...
... c_001_demo_win8=U;;;; [check_sakuli] CR LF
=======
...
...
...c_001_demo_win8=U;;;; [check_sakuli] LF
CR LF
=======
...
...
...c_001_demo_win8=U;;;; [check_sakuli] LF
CR LF
=======
``` 

* (imho, CR LF in the very last line of each packet is not necessary)
* the CR in the end of the first message is wrong

**Comment by christophd** [comment]
Force unix style line ending when writing gearman-cache file. Removed unnecessary new lines at the end of each packet
