### ISSUE TITLE
introduce sakuli.forwarder.gearman.cache.sendpause

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#187]
The screenshot history eventhandler relies on the livestatus having the status of the currently processed event available. 
When Sakuli sends cached packets before the current one, livestatus immediately has the current status while there are eventhandlers running to parse the screenshots of the events before. 

Problem is that all cached events get the message and screenshot image from the current status.   

Solution is to pause the transmission of cached results for a certain number fo seconds (sendpause) to let each eventhandler read the livestatus data of "his" event.

**Comment by christophd** [comment]
Feature of waiting a period of time in between the cached results has been already been there. 

The sakuli property is called "sakuli.forwarder.gearman.job.interval" and defines a period in milliseconds to wait between the result push operations. The implementation so far did only wait in case the previous job was still running. I changed this so the pause is always applied between cached result operations.
