### ISSUE TITLE
integrate 32 bit Go starter

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#194]
32 bit client systems are also still default in some environments.

**Comment by toschneck** [comment]
change current compiling to 32-bit

**Comment by toschneck** [comment]
fixed it with https://github.com/ConSol/sakuli-go-wrapper/commit/8c81c685835671e273149df7fba3466a41fe1f93. Seams like maven didn't setup the environment correctly. @simonmeggle can you verify it with the latest dev-version?
