### ISSUE TITLE
postHook: make check results available for postHook 

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#196]
That would make the postHook more flexible, i.e. 
- do certain things dependent on the check result
- have the possibility to write own result processors (i.e. write to file, write log entry, ...)

**Comment by simonmeggle** [comment]
Proposal: Sakuli writes formatted results to a new file descriptor which is read then by the go starter. This information is exported then to the postHook.

**Comment by simonmeggle** [comment]
Introduce default forwarder "JSON" which stores thes result in ''.cache/result.json''. 
Go Starter exports new variable $RESULT_JSON which can be used in the postHook.

**Comment by toschneck** [comment]
have been solved with #274. Results ca be parsed in postHook script.
Currently env `RESULT_JSON` will not be set, use latest `.json` file in log folder.
