### ISSUE TITLE
Rewrite Docker ENTRYPOINT script of sakuli-xxx-xfce

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#198]
- CMD in Dockerfile contains $SAKULI_TEST_SUITE, but the exec form of CMD does not expand environent variables at all. For that reason, the entrypoint script uses "eval" to re-expand the variable. -> If possible, we should avoid the eval, not least because the CMD looks like variable expansion here works, which is not the case. 
  Better expand $SAKULI_TEST_SUITE in the entrypoint script directly and omit the CMD statement completely. A handful of comment lines in the Dockerfile instead should explain what is done within the entrypoint script. 
- VNC startup is done regardless of the arguments given. For calling encrypt/help/version of Sakuli, this is needless. ->  rewrite the argument parsing so that VNC is started only for test execution and any other command.

**Comment by toschneck** [comment]
@simonmeggle i pushed the changes to branch `docker-playground`

**Comment by toschneck** [comment]
check after #218
