### ISSUE TITLE
sleep ambigous defined

### ISSUE THREAD

**Issue by frgithubaccount** [ConSol/sakuli#201]
sakuli Version 
sakuli-v1.1.0-SNAPSHOT

in js file 

``` .javascript
var testCase = new TestCase(60, 70);
var env = new Environment();
var screen = new Region();
//cert_accept.png  logged_off.png  log_off.png  pin_eingabe.png  settings_page.png  settings.png  weblogin.png
try {
env.sleep(2)
```

results in

``` .bash
InternalError: The choice of Java constructor sleep matching JavaScript argument types (number) is ambiguous; candidate constructors are: 
    class org.sakuli.actions.environment.Environment sleep(java.lang.Integer)
    class org.sakuli.actions.environment.Environment sleep(java.lang.Double) (RhinoScriptRunner.run#416(eval)#306)
```

**Comment by christophd** [comment]
Hm, that is interesting. Had not expected that to happen.

I changed the method signature sleep(java.lang.Double) to sleepMs(java.lang.Integer) so users can specify milliseconds to sleep here. I think this is the most convenient way of defining time units other than seconds. The sleep(java.lang.Integer) method is still there and expects values of seconds time unit.

**Comment by christophd** [comment]
After review with developers we found the bug in Rhino method mapping. Now sleep(java.lang.Double) is also available again with fixed parameter casting in Rhino js mapping
