### ISSUE TITLE
libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by lhoe** [ConSol/sakuli#202]
On Docker Startup libdc1394 cannot be initialized
Is this lib even needed? Is it Sikuli or VNC?

"high level programming interface for IEEE1394 digital camera"
http://packages.ubuntu.com/search?keywords=libdc1394-22

**Comment by toschneck** [comment]
![image](https://cloud.githubusercontent.com/assets/4659261/17320667/03877a52-5895-11e6-86cc-b83928770b85.png)

**Comment by simonmeggle** [comment]
Check after #218

**Comment by toschneck** [comment]
error is already solved
