### ISSUE TITLE
Sakuli-OMD-Labs Docker image (cloud-ready)

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#204]
after #203: 
using ansible-docker and Sakuli-Ansible-dropin-role
ready to use in OpenShift (Source2Image)

**Comment by simonmeggle** [comment]
[https://hub.docker.com/r/consol/sakuli-omd-labs-debian/](https://hub.docker.com/r/consol/sakuli-omd-labs-debian/)
[https://hub.docker.com/r/consol/sakuli-omd-labs-ubuntu/](https://hub.docker.com/r/consol/sakuli-omd-labs-ubuntu/)
[https://hub.docker.com/r/consol/sakuli-omd-labs-centos/](https://hub.docker.com/r/consol/sakuli-omd-labs-centos/)

Next step ist to include Sakuli add-ons into the OMD package.

**Comment by toschneck** [comment]
image as automateable build:
1) run `ansible-playbook` on build time, instead of ansible-container
2) Ansible playbook contains:
* wegt to github zip download like
```
ENV VERSION=dev
ENV VERSION=v1.0.1
wget https://github.com/ConSol/sakuli/archive/$VERSION.zip
```
* cleanup or remove `Makefile`
3) Write documentation: How to build a custom omd/sakuli installation and add some checks

**Comment by toschneck** [comment]
@simonmeggle 
Currently omd didn't resolve the timezone correctly. 
If I configure in the `docker-compose.yml` the timezone it doesn't get into the OMD view:
```.yml
omd-nagios:
    container_name: omd-nagios
    image: consol/sakuli-omd-labs-ubuntu
    ports:
    - 8043:443
    environment:
    - TZ=Europe/Berlin
    volumes:
    - ./omd_ansible_drop-in_role/:/root/ansible/dropin_role
```

The time displayed in the overview page is in ETC time:
![selection_008](https://cloud.githubusercontent.com/assets/4659261/19076728/44a5df74-8a4a-11e6-9bc8-e6590fd51005.png)

If I mount the localtime into the container, the problem go away:
```.yml
    volumes:
    - /etc/localtime:/etc/localtime
    - ./omd_ansible_drop-in_role/:/root/ansible/dropin_role
```
But I think this shouldn't be the expected behavior or?

**Comment by toschneck** [comment]
@simonmeggle Cleanup of DockerHub should be also be done:
```.bash
[tschneck]$ docker search sakuli
NAME                            DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
consol/sakuli-ubuntu-xfce       Sakuli end-2-end testing and monitoring co...   2                    [OK]
consol/sakuli-centos-xfce       Sakuli end-2-end testing and monitoring co...   2                    [OK]
consol/omd-labs-ubuntu-sakuli   OMD - Open Monitoring Distribution "labs" ...   2                    [OK]
consol/sakuli-omd-labs-ubuntu   OMD Labs (Ubuntu) + Sakuli E2E Add-Ons          0                    
consol/sakuli-omd-labs-debian   OMD Labs (Debian) + Sakuli E2E Add-Ons          0                    
consol/sakuli-omd-labs-centos   OMD Labs (CentOS) + Sakuli E2E Add-Ons          0                    

```

**Comment by toschneck** [comment]
@simonmeggle add template `tpl_s_sakuli_gearman` for:
```
define service {
  service_description            example_lm_18_1
  host_name                      sakuli_LM_client
  use                            tpl_s_sakuli_gearman
}
```

**Comment by toschneck** [comment]
@simonmeggle Template is already added, I just used the wrong docker image version. Forgot that the feature branch wasn't merged :-/
```
root@1f7dd30e3703:/opt/omd/sites/demo/etc/nagios/conf.d# cat sakuli_nagios_objects.cfg 
define service {
  name                           tpl_s_sakuli_gearman
  use                            generic-service,srv-pnp
  active_checks_enabled          0
  check_command                  check_dummy!3!'Did not receive any Sakuli result within 3 minutes.'
  check_freshness                1
  event_handler                  sakuli_screenshot_eventhandler
  event_handler_enabled          1
  freshness_threshold            180
  icon_image                     sakuli.png
  icon_image_alt                 Sakuli E2E test
  notes                          Sakuli E2E results received by mod-gearman
  passive_checks_enabled         1
  is_volatile                    1
  register                       0
}

```

**Comment by toschneck** [comment]
TODOs:
* Site name from Docker Build `ARG`
* List of data folders to store in persistent volume:
  * Ansible hook for linked folders to persistent volume
* Example in https://github.com/ConSol/sakuli-examples

**Comment by simonmeggle** [comment]
then head to #237
