### ISSUE TITLE
Add an easy method for changing property values dynamicly in the runtime

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#227]
Add an method like `env.setPropery(key, value)` to the Sakuli API, so users have the possibility to change some properties of the `testsuite.properties` during the execution of an testcase.
Check following points:
* Should it be possible to override all Properties or just a few predefined?
  * If not all properties are support, throw an excpetion
* What should happen if more testcases will follow? Start with the former properties?
  * Dynamic Spring Property mechanism

**Comment by simonmeggle** [comment]
> all Properties or just a few predefined
I would prefer to allow only a subset. 
> ...more testcases will follow?
Each test case should start with its default properties; properties should be set in each case. Changing properties at suite-level can lead to unexpected behaviour, when case 1 raises an exception *before* the property gets set. Case 2 will then start with a wrong (default) property.

**Comment by toschneck** [comment]
will be done if somebody really need it :wink:

**Comment by toschneck** [comment]
because nobody asked for that point anymore, i close the issue
