### ISSUE TITLE
Automatic parsing from dashed env vars

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#238]
Find a way to map env vars like `SAKULI_LOG_FOLDER` to the sakuli property `sakuli.log.folder` automatically. 

This will be helpful to manage docker containers from the outside during runtime like in an openshift deployment.

2 Possible ways to go:
* Extend the SpringPropertyLoader so that this kind of environment vars could be also read `SakuliPropertyPlaceholderConfigurer` 
* (alternative) Extend the go wrapper, to do the env parsing: https://github.com/spf13/viper, https://github.com/rickar/props

**Example:** `openshift.sakuli.gitvolume.pod.run.yaml`
***old***
```.yaml
      volumeMounts:
      - mountPath: /headless/sakuli/testsuite
        name: vol-testsuite
      args:
        - run
        - /headless/sakuli/testsuite/${GIT_TEST_SUITE_PATH}
        - -D
        # must be a writable path
        - sakuli.log.folder=/headless/sakuli/logs
        - -D
        # not needed in openshift environment
        - sakuli.forwarder.gearman.cache.enabled=false
```

***new***
```.yaml
      volumeMounts:
      - mountPath: /headless/sakuli/testsuite
        name: vol-testsuite
      env:
      - name: SAKULI_TEST_SUITE
        value: headless/sakuli/testsuite/${GIT_TEST_SUITE_PATH}
      - name: SAKULI_LOG_FOLDER
        value: $SAKULI_ROOT/logs

```

**Comment by toschneck** [comment]
see `TODO #238`

**Comment by simonmeggle** [comment]
Try to read all properties in ``sakuli-default.properties`` from the environment. If found, it will overwrite the property value.
