### ISSUE TITLE
Installation automation

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#24]
http://izpack.org/

**Comment by simonmeggle** [comment]
`export SAKULI_HOME=/home/sakuli_user/sakuli`

**Comment by toschneck** [comment]
TODO:
* Add environment script for settings path with `SAKULI_HOME`
* Update documentation
* Check if sahi could attached to zip installation also
* Update docker images

**Comment by toschneck** [comment]
add installation packages:
* FirefoxPortable
* QRes http://qres.sourceforge.net/
* evtl. GitPortable
