### ISSUE TITLE
Grafana Template doesn't support png

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#265]
The new grafana template can't handle with `.png` as screenshot formates. Similar to #208 .
Need to be fixed before #174 can be done!
![image](https://user-images.githubusercontent.com/4659261/28928524-b001a7f0-786d-11e7-8223-39e272c6597f.png)

**Comment by simonmeggle** [comment]
Fixed & created PR: https://github.com/Griesbacher/histou/pull/12
