### ISSUE TITLE
JSON File Output forwarder

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#274]
To be able to read out the Sakuli test results from the admin UI, write out the resulsts as Json to `log.folder/result_<timestamp>.json`. It be should be enabled by default

Also add all Sakuli/Sahi action to the json (maybe as sorted sublist in TestSteps, see `RhinoAspect.java`)
Bsp Log: `Region.waitForImage() - wait for image for x seconds with arg(s) [gedit.png, 10]`
 Json vorschlag:
```.json
{
  "object": "Region",
  "method": "waitForImage",
  "arguments": ["gedit.png", 10],
  "message":"wait for image for x seconds",
  "documentation":"http://consol.github.io/sakuli/v1.1.0-SNAPSHOT/index.html#Region.waitForImage"
}
```
Modify the log output maybe to: `Region.waitForImage(gedit.png, 10) - wait for image 'gedit.png' for 10 seconds`

**Comment by tnobody** [comment]
More information about usage: 
https://github.com/ConSol/sakuli-admin/issues/3
https://github.com/ConSol/sakuli-admin/issues/5

**Comment by toschneck** [comment]
@joroboro should be merged in dev AFTER release #

**Comment by tnobody** [comment]
currently Dateformats aren't unified:

creationDate: "2017-10-04T15:49:31.689Z"

but stopDate or startDate:

"Oct 4, 2017 3:49:56 PM"

also the dateformat in filenames is different (but thats ok for me). 
Using ISO-Dates everywhere would be nice since it's pretty easy to use in Javascript :)

**Comment by toschneck** [comment]
@joroboro can you change this?

**Comment by toschneck** [comment]
Issue with method `dragAndDrop` if  arg is an `Region` object itself
