### ISSUE TITLE
forward also case- and step results

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#304]
Send the results optionally also on a case/step basis. 
Change proposals: 

**class TestCase**
old usage: 
```
var testCase = new TestCase(20,30[, path]);
```
new usage: 
```
var testCase = new TestCase(["custom-caseId", 20,30, "optional-image-path"]);
TestCase.addImagePaths(path);
```
* the first parameter can overwrite the case id derived from the case folder name
* parameter 2 and 3 specify the warning/critical threshold
* parameter `path` will be deprecated => use `TestCase.addImagePaths(imagePaths)` instead to overwrite the default image search path

**method _endOfStep_**
old usage:
```
TestCase.endOfStep("foo", 10);
```
new usage:
```
TestCase.endOfStep("foo", 10,[ 20, true]);
``` 

* add a critical threshold parameter (keep compatibility to warning-only definitions!)
* add a forward flag which sends the **step** result to forwarder. For monitoring forwarders the following object names are used: 
** _hostname_: (taken from forwarder definition)
** _service_description_: `${testsuite.id}_${testcase.id}_${teststep.id}`

**method _saveResult()_**
old usage: 
```
testCase.saveResult();
```
new usage: 
```
TestCase.saveResult(true)
```
* add a forward flag which sends the **case** result to forwarder. The case execution will stop afterwards. For monitoring forwarders the following object names are used: 
** _hostname_: (taken from forwarder definition)
** _service_description_: `${testsuite.id}_${testcase.id}` (as defined by case folder name or TestCase object initialization, see above)

:warning: **General note:** Rhino script currently **DON'T** support named parameter like ES2015 Script does. Something like  `testCase.endOfStep({stepName: "Calculation", optForward: true});` is not possible :cry:

**Comment by toschneck** [comment]
**Change internal forwarder implementation:**
* Be able to generate data separately for:
  * TestSuite `TeardownServiceHelper.invokeTeardownServices`
  * TestCase
  * TestStep
* For services which don't support the new modes throw Exception "not supported"
