### ISSUE TITLE
Pre-parsing step definitons

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#31]
Steps are defined at the end of every logical section of a test. Hence, only at the very end of a test all step names are known to Sakuli. This is not the case if there is an exception during the tests; all steps after the exit point won't be sent to Nagios. PNP4Nagios then assumes that the number of data sources has changed, the XML file will be updated only with the number fo steps which were passed until the exception. => RRDtool will only graph some data sources.

Possible solution: parse tets case before execution so that all steo definitions are known to Sakuli. Then, even in the case of an exception, all perfdata labels can be sent to Nagios which are neccessary for pnp4nagios to print the graph properly.

**Comment by toschneck** [comment]
parse each line for a regex lik e `.*\.endOfStep\(".*\)`
* _include files should be also parsed
* uncomment code should be excluded

**Comment by simonmeggle** [comment]
c:L highly interested....

**Comment by simonmeggle** [comment]
Steps without runtime should have value "u"

**Comment by toschneck** [comment]
Already implemented:
* Sakuli now creates for each test case an file `.sakuli-steps-cache` if the test execution was no in the state `ERROR`
* To create also for not reachable steps the step definitions, Sakuli reads in on the startup the cached step definitions in `.sakuli-steps-cache` file.
* So now, all steps which won't be reached will be shown in the results as Steps with the state `INIT`
  * Gearman forwarder: will get the performance data in the format `s_001_001_STEP_NAME=U;;;; ` with the state `UNKNOWN`
  * Database forwarder: the steps get the following values `result: -1` and `result_desc: INIT`

**Comment by toschneck** [comment]
TODO:
* check performance data graphs output with long term data
* add modified nagios scripts to git

**Comment by sni** [comment]
I assume the problem with the "not_ok" state occurs whenever there is more than one result in one rrd timeslot. This might happen when a check is rescheduled immediatly after a failed one. "state" then contains a float value instead if an interger 0-3.

**Comment by simonmeggle** [comment]
Todo: draw tickler for UNKN values (RPN calculation)
