### ISSUE TITLE
_div can't access Element

### ISSUE THREAD

**Issue by E2EUserTest** [ConSol/sakuli#321]
I'm trying to access a div element with _div("divTo"),
but it doesn't find it, please help me out?
After that i'd like to write something into it is that possible with _value for editable div elements?

`<div id="divTo" class="rwW" spellcheck="false" style="height: 19px;" contenteditable="true">&nbsp;</div>`

best regards

**Comment by simonmeggle** [comment]
You can use the [Sahi Controller](https://sahipro.com/docs/using-sahi/sahi-controller.html) to get the correct accessor methods for the div element. 
Does [this issue](https://community.sahipro.com/forums/discussion/2712/setting-value-in-div-element) contain any helpful information? 
If not, I would suggest to use Sikuli to enter text into the div element:
`screen.find("screenshotofthediv").click().type("yourtext");`

**Comment by E2EUserTest** [comment]
hey, thanks for your answer, the problem is I can find the element but Sakuli doesn't.
The Sahi Controller shows the element but isn't able to do the test.
It gives as response a undefined..

Is it possible that Sakuli can't handle editable div elements?

**Comment by E2EUserTest** [comment]
@toschneck thanks for the input, but it's the same domain. I am even able to fill other forms which are textboxes at the same page, but it seems like editable div tags are not supported!?

**Comment by E2EUserTest** [comment]
sorry i messed up with the label, by accidentally closing.

**Comment by toschneck** [comment]
@E2EUserTest ok it sounds that's a Sahi related topic. So the only thing I can do is to point at the sahi forum: https://community.sahipro.com/forums/

Alternatively we can offer you, that an engineer of our team will do a payed remote session with you. In this case write a mail to sakuli@consol.de
