### ISSUE TITLE
Alphabetical sorting in API docs

### ISSUE THREAD

**Issue by s1hofmann** [ConSol/sakuli#325]
API calls should be sorted alphabetically for easier searches.

See example:

- Application.setSleepTime(seconds)
- Application.getRegion()
- Application.getRegionForWindow(windowNumber)
- Application.getName()

**Comment by toschneck** [comment]
I think the sorting depends on the order of the methods of  http://consol.github.io/sakuli/latest/index.html#Region.waitForImage
