### ISSUE TITLE
`Application.close()` fails on Windows 10

### ISSUE THREAD

**Issue by s1hofmann** [ConSol/sakuli#327]
In our recent test the call to `Application.close()` in a `finally` block failed and the application dind't closed.

**Comment by toschneck** [comment]
entrypoint should be: https://github.com/sakuli/SikuliX-2014/blob/b253bed3d45c0fefe7517b5561f6754d227a1a29/API/src/main/java/org/sikuli/natives/WinUtil.java#L263

**Comment by s1hofmann** [comment]
```Application.open()``` on Windows 10 returns a different PID than the actual program running, e.g.

```
DEBUG [2018-07-12 13:49:04.370] - verify app calc.exe PID:6052 is running
INFO  [2018-07-12 13:49:04.466] - Application 'calc.exe PID:6052' is running
```

Actual running application:

```
Calculator.exe, PID:2652
```
