### ISSUE TITLE
Update certificate handling with IE in documentation 

### ISSUE THREAD

**Issue by s1hofmann** [ConSol/sakuli#328]
Sahi proxy requires one to import certificates generated by Sahi proxy.
Documentation only contains a sample for Firefox, but IE requires different actions.

**Comment by toschneck** [comment]
entrypoint should be: https://github.com/sakuli/SikuliX-2014/blob/b253bed3d45c0fefe7517b5561f6754d227a1a29/API/src/main/java/org/sikuli/natives/WinUtil.java#L263

**Comment by toschneck** [comment]
see http://sahipro.com/docs/using-sahi/sahi-configuration-basic.html#Configure%20SSL
