### ISSUE TITLE
SSL Error, Handshake

### ISSUE THREAD

**Issue by E2EUserTest** [ConSol/sakuli#333]
Hi there, i am using the dockerized version of sakuli.
I am trying to surf any site with ssl and i get from firefox no_cypher_overlap, when i use sahi directly i get and exception for the "new" certificate but not when i use sakuli.

I don't get any usefull information out of sahi, wireshark captures show that the handshake seems to be broken.

The only change i made is to upgrade the image to the new firefox, which is needed for the site i am testing.

**Comment by s1hofmann** [comment]
Did you run your Sakuli tests after you imported the self-signed certificates via Sahi dashboard?
If not, did you add the generated certificates to your Docker image when re-running the tests?

**Comment by E2EUserTest** [comment]
ok seems like sakuli isn't able to generate any certificates using sahi.
after generating a certificate with sahi, sakuli just works fine.

i wasn't aware of that, maybe someone should mention this in the documentation and
sakuli should be able, thru sahi, to generate certificates too.

**Comment by s1hofmann** [comment]
It's explained in [the Sakuli docs](http://consol.github.io/sakuli/v1.3.0-SNAPSHOT/index.html#sahi-https) how to handle certificates via Sahi. Alternatively, you could prepend your test with a helper to accept certificates via test actions.

**Comment by E2EUserTest** [comment]
@s1hofmann exactly that's the point, since sahi handles the the connections you would guess that it should be able to generate certificates, even if it's called by the suite sakuli.

i mean't with the part in the documentation that it is not clear that **sakuli** as suite is **not able** to generate a ssl certificate, i think this should be mentioned explicitly.

thanks for your time
