### ISSUE TITLE
Firefox 35 unable to load full page on first try (upgrade sahi to v5?)

### ISSUE THREAD

**Issue by vasekch** [ConSol/sakuli#51]
After update to Firefox 35 Sakuli is unable to load starting page correctly - shows only html, no images nor css are loaded. When manually execute reload of the page everything is loaded and test proceeds. After downgrading to Firefox 34 everything is ok.

Even if I start pure Sahi on FF 35, I have issues starting sahi controller (alt + doubleclick does not work) - loading a page is ok.

I have found that Sahi guys released next version of Sahi OS v5 (it's 3 months ago, unfortunately touch features has not been opensourced yet) http://sourceforge.net/projects/sahi/files/sahi-v5

Change log mentions improved compatibility with FF 20+ but the thing is that FF 35 was released just a month ago (2 months after Sahi v5). Would you give your opinion which direction to look for fix?

head of changelog.txt
```
04 Jun 2014
-----------
Sahi 5.0

* Features
	* New APIs:
		    _copyFile
			_frame, _fieldset
			_setXHRReadyStatesToWaitFor
			_getSelectionText, _selectRange, _selectTextRange
			_isIE6, _isIE7, _isIE10, _isIE11, _isIE11Plus support
	* New and improved Sahi Start Page, Sahi Dashboard and Sahi Controller
	* Added Sahi Pro DOCS link on the Sahi Dashboard
	* Added notepad++/textpad support for syntax highlighting and Autocomplete features
	* Added "domainfix.txt" to the configure link page through the Dashboard
	* Added support for Enabling Traffic Logs
	* Added support for user_extension.js
	* Added "Bin" link on dashboard for MAC
	* Added executeSahi API support for Java and Ruby
	
* Bugfixes
	* Sahi compatibility issue with ie 10,11
	* Sahi compatibility issue with firefox 20+
	* Elements can now be identified with custom attributes using Sahi Controller.
	* Proxy setting for Opera browser
	* Modified _scriptStartTime() API
	* Fixed improper closing dashboard for Mac and Linux.
	* Added support to set the proxy on safari browser automatically on Mac.
...
```

Do you plan upgrading Sahi inside Sakuli?

**Comment by toschneck** [comment]
I just quickly tested this problem here with my **Firefox Portable Version 35.0.1** (http://www.heise.de/download/firefox-portable.html) and it works as  normal as the former version do. Unfortunately I can't currently test it with the "normal" version, but maybe this will solve your problem.

I personal execute all my tests with the portable version of the Browsers, because only in this setup guarantees that the browser settings won't be affected from some company security policies. To configure other browser in sahi see [Troubleshooting - no browsers in dashboard](https://github.com/ConSol/sakuli/blob/master/docs%2Ftroubleshooting-sakuli-client.md#no-browsers-in-dashboard).

Furthermore we currently plan to upgrade Sakuli to the new Sahi OS v5 within the next few months, before we release the 1.0 version of Sakuli. If you want, you can track the issue #7.

**Comment by vasekch** [comment]
Portable version seems to have same issue for me, maybe it's my site specific thing, I will investigate later and report here.

**Comment by toschneck** [comment]
Unfortunately on my setup, Sahi  sets the proxy correctly to port 9999. Maybe it is better to bring Sahi standalone running and after set use the same installation with sakuli. We sometimes had the issue that Sahi can't configure the proxy, when the current user have not the necessary rights to modify the browser installation folder or config.

One thing you can check furthmore is, if your site will have some content which is load over a HTTPS/SSL ensured connection, check if **ALL**  SSL certificates are imported like described here: http://sahipro.com/docs/using-sahi/sahi-configuration-basic.html#Configure SSL

One more thing, the version we used for all our Sakuli stuff is stored under http://labs.consol.de/sakuli/install/3rd-party/install_sahi_v44_20130429.jar if you want to test it with these.

**Comment by vasekch** [comment]
Proxy setting has definitely something to do with profile directories. Something broke copying Sahi template profile to portable profile dir on my instalation, but it's not a big deal.

No content on my test page is accessed via HTTPS (I know it needs certificate tricks, so I left it out).

Yes, I used .jar from your source.

I will get back to this issue later, thanks for the tips so far.
