### ISSUE TITLE
Sakuli start hangs when --browser is invalid

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#68]
e.g. `--browser fire` ends in

`INFO [2015-03-30 13:46:30] - Sahi.Script-Runner starts!`

STARTER HANGS AFTER THAT.

**Comment by toschneck** [comment]
It should be the same wenn you set a wrong value to the property 'testsuite.browser'. 
We just forward these name to sahi, maybe it will be better with version v5 in #7
