### ISSUE TITLE
test sahi v5 compatibility & upgrade

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#7]

**Comment by toschneck** [comment]
first try - sakuli current can run with sahi5, pushed the installer image to http://labs.consol.de/sakuli/install/3rd-party/install_sahi_v50_20141105.jar

next steps:
* add jar as maven resource to pom
* check aspects for report and logging
* check #11 port config
* check starter vor javaDSL
* check if hock for syncron status calls is still necessary

**Comment by simonmeggle** [comment]
Installation & version
