### ISSUE TITLE
testsuite.suite gets overwritten

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#72]
Under certain circumstances(?), the suite file gets rewritten - and is empty sometimes.

**Comment by toschneck** [comment]
Wollen wir den Issue wieder schließen? 


Von: "Simon Meggle" <notifications@github.com> 
An: "ConSol/sakuli" <sakuli@noreply.github.com> 
Gesendet: Montag, 13. April 2015 10:03:26 
Betreff: [sakuli] testsuite.suite gets overwritten (#72) 



Under certain circumstances(?), the suite file gets rewritten - and is empty sometimes.

**Comment by simonmeggle** [comment]
Ich habe keine Logfiles mehr von der PBB bekommen. Würde sagen ja. 

Kannst Du das File sicherheitshalber nur dann schreiben, wenn es was zu ersetzen gab? Das fände ich schöner, wie wenn Sakuli das File grundlos jedesmal neu rausschreibt. 



----- Ursprüngliche Mail -----
Von: "toschneck" <notifications@github.com>
An: "ConSol/sakuli" <sakuli@noreply.github.com>
CC: "Simon Meggle" <Simon.Meggle@consol.de>
Gesendet: Freitag, 17. April 2015 10:49:18
Betreff: Re: [sakuli] testsuite.suite gets overwritten (#72)

Wollen wir den Issue wieder schließen? 


Von: "Simon Meggle" <notifications@github.com> 
An: "ConSol/sakuli" <sakuli@noreply.github.com> 
Gesendet: Montag, 13. April 2015 10:03:26 
Betreff: [sakuli] testsuite.suite gets overwritten (#72) 



Under certain circumstances(?), the suite file gets rewritten - and is empty sometimes. 

— 
Reply to this email directly or view it on GitHub . 




---
