### ISSUE TITLE
hidden Step functionality

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#73]
testCase.endOfStep("foobar",0,true);

3rd parameter = optional => hide this step. 
Would be helpful for "auxilary" steps which should not be measured, e.g. klicking through unimportant parts of an application.

**Comment by simonmeggle** [comment]
See also issue #73

**Comment by simonmeggle** [comment]
Hidden steps are collected in one perfdata label:

    s_[caseno]_[stepcount+1]_hiddensteps

**Comment by toschneck** [comment]
waiting for some one who need this 😉

**Comment by toschneck** [comment]
not needed
