### ISSUE TITLE
new method: testCase.startTimer

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#76]
add functionality to define super-steps 

testCase.startOfSuperStep("user_report");
testCase.endOfSuperStep("user_report",120);

Supersteps should not be reported as Nagios perfdata, but can also generate WARNING states if thresholds are exceeded.

**Comment by simonmeggle** [comment]
See also #73

**Comment by simonmeggle** [comment]
= separate timer
Proposal: 

    startTimer("name");
    stopTimer("name", warning, critical);

Separate Graph for timers with lines (=not stacked); perfdata: 

    t_[caseid]_[name]

**Comment by toschneck** [comment]
waiting for some one who need this :wink:

**Comment by toschneck** [comment]
not needed
