### ISSUE TITLE
rename function names 

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#8]
Sakuli.Environment.js: 

pasteClipboard => pasteFromClipboard?
or
copyIntoClipboard => copyClipboard? 

decryptSecret => decrypt (all other decrypt methods do not contain "Secret")

Duplicate Definition (environment & screen): 
paste 
pasteMasked 
pasteAndDecrypt 
type 
typeMasked 
typeAndDecrypt

**Comment by toschneck** [comment]
Functions in Environment and Region:
![typing_util_functions](https://cloud.githubusercontent.com/assets/4659261/6285335/e8cba8ea-b8fa-11e4-827c-9709329695f0.png)

**Comment by simonmeggle** [comment]
Will not be changed: 
All these methods belong logically to **Environent**. 
But they remain also in **Region** to daisy chain method calls which return a region object, e.g.

    screen.waitForImage("foo",3).sleep().type("bar");
