### ISSUE TITLE
Create Thruk custom menu for screenshot history

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#90]
As of today, screenshots are stored on the client's filesystem only. The screenshot contained in service details of Nagios gets lost on the next check result.
This is not useable for support guys who only get Nagios messages, but have no access to the clients. If the check has recovered, there is no way to inspect earlier screenshots.

**Comment by toschneck** [comment]
maybe @sni  have some idea how to solve this in thruk?

**Comment by sni** [comment]
Thruk just shows the current status from nagios. If screenshots are stored somewhere in a folder accessible by web, you could just add a link in thruk via "show_custom_vars" or "notes_url" or something like that.

**Comment by simonmeggle** [comment]
Option: Eventhandler which gets fired on CRITICAL, checks for "Exception" and tries to pull out url_encoded image data to store on filesystem.
