### ISSUE TITLE
Gearman encryption

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#91]

**Comment by simonmeggle** [comment]
See https://github.com/sni/mod_gearman/blob/master/common/gm_crypt.c for AES encryption.

**Comment by simonmeggle** [comment]
Enable encyrption on server side: 
* store password in ``/omd/sites/OMD_SITE/etc/mod-gearman/secret.key``
* enable encryption in ``/omd/sites/OMD_SITE/etc/mod-gearman/server.cfg`` => ``encryption=yes``

**Comment by toschneck** [comment]
* Use branch `hotfix/lhm`
* Deliver as Docker-Image `consol/sakuli-ubuntu-xfce:1.0.2-lhm` (adjust docker build setup to use for this tag the git-hub branch `hotfix/lhm`)
